import { Doctor, Patient, ScreeningRecord } from '../types';
import { SAMPLE_FUNDUS_IMAGES } from '../assets/fundusImages';

export const DEFAULT_DOCTORS: Doctor[] = [
  {
    id: 'DOC-KA-0941',
    name: 'Dr. Ananya Sharma, MD',
    email: 'ananya.sharma@health.gov.in',
    role: 'District Ophthalmic Medical Officer',
    facility: 'Ramanagara District Primary Eye Care Center',
    district: 'Ramanagara',
    state: 'Karnataka',
    registrationNumber: 'KMC-78921-2015',
  },
  {
    id: 'DOC-KA-0942',
    name: 'Dr. Vikram Hegde, MS (Ophth)',
    email: 'vikram.hegde@district-health.org',
    role: 'Visiting Vitreo-Retina Consultant',
    facility: 'Channapatna Sub-District Hospital',
    district: 'Ramanagara',
    state: 'Karnataka',
    registrationNumber: 'KMC-64102-2012',
  },
];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'DR-2026-001245',
    fullName: 'Arun Kumar',
    age: 54,
    dateOfBirth: '1972-04-12',
    gender: 'male',
    phone: '+91 98452 11094',
    village: 'Channapatna Rural',
    subDistrict: 'Channapatna',
    district: 'Ramanagara',
    diabetesType: 'type_2',
    diabetesDurationYears: 8,
    hbA1c: 8.6,
    hypertension: true,
    emergencyContact: {
      name: 'Sunita Kumar',
      relationship: 'Spouse',
      phone: '+91 98452 11095',
    },
    createdAt: '2026-02-10T10:00:00Z',
    lastVisitAt: '2026-10-08T09:42:00Z',
    screeningCount: 3,
    currentSeverity: 'moderate',
    currentReferralStatus: 'urgent_1_2_weeks',
  },
  {
    id: 'DR-2026-001246',
    fullName: 'Meenakshi Sundaram',
    age: 62,
    dateOfBirth: '1964-08-19',
    gender: 'female',
    phone: '+91 97410 88234',
    village: 'Magadi Town Ward 4',
    subDistrict: 'Magadi',
    district: 'Ramanagara',
    diabetesType: 'type_2',
    diabetesDurationYears: 12,
    hbA1c: 7.2,
    hypertension: false,
    emergencyContact: {
      name: 'Ganesh Sundaram',
      relationship: 'Son',
      phone: '+91 97410 88235',
    },
    createdAt: '2026-01-15T09:30:00Z',
    lastVisitAt: '2026-09-24T11:15:00Z',
    screeningCount: 3,
    currentSeverity: 'mild',
    currentReferralStatus: 'routine',
  },
  {
    id: 'DR-2026-001247',
    fullName: 'Rajeshwari Patil',
    age: 58,
    dateOfBirth: '1968-11-03',
    gender: 'female',
    phone: '+91 94481 44521',
    village: 'Kanakapura South',
    subDistrict: 'Kanakapura',
    district: 'Ramanagara',
    diabetesType: 'type_2',
    diabetesDurationYears: 15,
    hbA1c: 10.4,
    hypertension: true,
    emergencyContact: {
      name: 'Basavaraj Patil',
      relationship: 'Spouse',
      phone: '+91 94481 44522',
    },
    createdAt: '2026-05-18T14:20:00Z',
    lastVisitAt: '2026-10-07T16:00:00Z',
    screeningCount: 2,
    currentSeverity: 'severe',
    currentReferralStatus: 'emergency',
  },
  {
    id: 'DR-2026-001248',
    fullName: 'Suresh Patel',
    age: 49,
    dateOfBirth: '1977-01-29',
    gender: 'male',
    phone: '+91 96112 39081',
    village: 'Bidadi Industrial Cross',
    subDistrict: 'Ramanagara',
    district: 'Ramanagara',
    diabetesType: 'type_2',
    diabetesDurationYears: 2,
    hbA1c: 6.8,
    hypertension: false,
    createdAt: '2026-10-08T08:30:00Z',
    screeningCount: 0,
    currentSeverity: 'healthy',
    currentReferralStatus: 'none',
  },
  {
    id: 'DR-2026-001249',
    fullName: 'Lakshmi Devi',
    age: 67,
    dateOfBirth: '1959-06-14',
    gender: 'female',
    phone: '+91 99004 55198',
    village: 'Harohalli Hobli',
    subDistrict: 'Kanakapura',
    district: 'Ramanagara',
    diabetesType: 'type_2',
    diabetesDurationYears: 9,
    hbA1c: 8.1,
    hypertension: true,
    createdAt: '2026-09-02T10:45:00Z',
    lastVisitAt: '2026-10-05T12:00:00Z',
    screeningCount: 1,
    currentSeverity: 'healthy',
    currentReferralStatus: 'none',
  },
  {
    id: 'DR-2026-001250',
    fullName: 'Venkatachalaiah Gowda',
    age: 64,
    dateOfBirth: '1962-03-22',
    gender: 'male',
    phone: '+91 98801 22394',
    village: 'Kudur Grama',
    subDistrict: 'Magadi',
    district: 'Ramanagara',
    diabetesType: 'type_2',
    diabetesDurationYears: 11,
    hbA1c: 9.2,
    hypertension: true,
    createdAt: '2026-03-12T11:00:00Z',
    lastVisitAt: '2026-10-06T15:20:00Z',
    screeningCount: 2,
    currentSeverity: 'moderate',
    currentReferralStatus: 'urgent_1_2_weeks',
  },
  {
    id: 'DR-2026-001251',
    fullName: 'Shailaja Kumari',
    age: 51,
    dateOfBirth: '1975-09-17',
    gender: 'female',
    phone: '+91 94803 77112',
    village: 'Tavarekere Block',
    subDistrict: 'Magadi',
    district: 'Ramanagara',
    diabetesType: 'type_2',
    diabetesDurationYears: 4,
    hbA1c: 7.0,
    hypertension: false,
    createdAt: '2026-04-20T09:10:00Z',
    lastVisitAt: '2026-09-18T10:30:00Z',
    screeningCount: 2,
    currentSeverity: 'healthy',
    currentReferralStatus: 'none',
  },
  {
    id: 'DR-2026-001252',
    fullName: 'Mohammed Rafiq',
    age: 56,
    dateOfBirth: '1970-12-05',
    gender: 'male',
    phone: '+91 97312 90445',
    village: 'Kylancha Cross',
    subDistrict: 'Ramanagara',
    district: 'Ramanagara',
    diabetesType: 'type_2',
    diabetesDurationYears: 7,
    hbA1c: 8.4,
    hypertension: true,
    createdAt: '2026-05-02T13:00:00Z',
    lastVisitAt: '2026-10-04T11:40:00Z',
    screeningCount: 2,
    currentSeverity: 'mild',
    currentReferralStatus: 'routine',
  },
  {
    id: 'DR-2026-001253',
    fullName: 'Prabhavathi R.',
    age: 60,
    dateOfBirth: '1966-07-28',
    gender: 'female',
    phone: '+91 99805 44102',
    village: 'Solur Village',
    subDistrict: 'Magadi',
    district: 'Ramanagara',
    diabetesType: 'type_2',
    diabetesDurationYears: 13,
    hbA1c: 9.8,
    hypertension: true,
    createdAt: '2026-06-11T10:15:00Z',
    lastVisitAt: '2026-10-07T14:10:00Z',
    screeningCount: 2,
    currentSeverity: 'severe',
    currentReferralStatus: 'emergency',
  },
  {
    id: 'DR-2026-001254',
    fullName: 'Narayana Swamy',
    age: 71,
    dateOfBirth: '1955-02-10',
    gender: 'male',
    phone: '+91 94490 12876',
    village: 'Ijoor Ward',
    subDistrict: 'Ramanagara',
    district: 'Ramanagara',
    diabetesType: 'type_2',
    diabetesDurationYears: 16,
    hbA1c: 8.9,
    hypertension: true,
    createdAt: '2026-02-28T09:40:00Z',
    lastVisitAt: '2026-10-01T10:00:00Z',
    screeningCount: 3,
    currentSeverity: 'moderate',
    currentReferralStatus: 'urgent_1_2_weeks',
  },
];

export const INITIAL_SCREENINGS: ScreeningRecord[] = [
  // Arun Kumar - Visit 1 (June 2026): Mild DR
  {
    id: 'SCR-2026-0112',
    patientId: 'DR-2026-001245',
    visitNumber: 1,
    date: '2026-06-10',
    time: '10:15 AM',
    timestamp: 1781086500000,
    eye: 'OD',
    doctorName: 'Dr. Ananya Sharma, MD',
    doctorId: 'DOC-KA-0941',
    imageSource: 'fundus_camera',
    imageUrl: SAMPLE_FUNDUS_IMAGES.MILD_DR,
    quality: {
      focusBlurScore: 92,
      illuminationScore: 94,
      fieldOfViewScore: 90,
      centeringScore: 93,
      overallScore: 92,
      status: 'good',
      reasons: [],
    },
    reviewStatus: 'confirmed_by_doctor',
    isRecaptureNeeded: false,
    aiResult: {
      imageId: 'IMG-SEED-01',
      imageValid: true,
      severity: 'mild',
      icdrLevel: 1,
      confidence: 88,
      trustReport: {
        imageQualityScore: 92,
        modelConfidence: 88,
        lesionEvidenceScore: 82,
        xaiAgreementScore: 89,
        overallTrustScore: 88,
        status: 'ai_supported',
        explanation: 'AI identification of isolated microaneurysms supported by high field clarity and optical sharpness.',
        safetyNote: 'AI screening decision support. Physician review confirmed.',
      },
      structures: {
        opticDisc: {
          detected: true,
          confidence: 96,
          location: { x: 73, y: 50, radius: 12 },
          cupToDiscRatio: 0.35,
          statusNotes: 'Sharp neuroretinal rim; no disc pallor or swelling.',
        },
        fovea: {
          detected: true,
          confidence: 94,
          location: { x: 44, y: 51, radius: 9 },
          macularEdemaRisk: 'low',
          statusNotes: 'Foveal avascular zone intact; no clinically significant macular edema.',
        },
        bloodVessels: {
          segmented: true,
          tortuosityIndex: 'mild',
          arteriovenousNicking: false,
          caliberScore: 88,
        },
        microaneurysms: {
          detected: true,
          count: 5,
          confidence: 89,
          locations: [
            { id: 'ma-1', type: 'microaneurysm', x: 38, y: 45, confidence: 91, quadrant: 'macular' },
            { id: 'ma-2', type: 'microaneurysm', x: 33, y: 58, confidence: 88, quadrant: 'inferior_temporal' },
            { id: 'ma-3', type: 'microaneurysm', x: 27, y: 40, confidence: 85, quadrant: 'superior_temporal' },
          ],
        },
        exudates: {
          detected: false,
          count: 0,
          confidence: 92,
          hasMacularThreat: false,
          locations: [],
        },
        hemorrhages: {
          detected: true,
          count: 2,
          confidence: 84,
          classification: 'dot_blot',
          locations: [
            { id: 'h-1', type: 'hemorrhage', x: 36, y: 64, confidence: 86, quadrant: 'inferior_temporal' },
          ],
        },
        neovascularization: {
          detected: false,
          confidence: 98,
          locationType: 'none',
          urgentSurgicalFlag: false,
        },
      },
      evidenceSummary: [
        '5 isolated microaneurysms detected in temporal macular arcade',
        '2 discrete dot-and-blot hemorrhages',
        'Zero hard exudates or macular edema signs',
      ],
      suggestedReferral: 'routine',
      suggestedFollowUpWeeks: 12,
      managementSuggestion: 'Glycemic and blood pressure stabilization. Repeat screening in 3 months.',
      analyzedAt: '2026-06-10T10:18:00Z',
    },
    doctorReview: {
      decision: 'continue_current_plan',
      doctorNotes: 'Early background retinopathy. Counselled regarding strict fasting blood sugar control and HbA1c target < 7%.',
      followUpDate: '2026-08-15',
      doctorName: 'Dr. Ananya Sharma, MD',
      doctorId: 'DOC-KA-0941',
      decidedAt: '2026-06-10T10:25:00Z',
    },
  },

  // Arun Kumar - Visit 2 (August 2026): Mild DR (Stable)
  {
    id: 'SCR-2026-0428',
    patientId: 'DR-2026-001245',
    visitNumber: 2,
    date: '2026-08-16',
    time: '11:20 AM',
    timestamp: 1786879200000,
    eye: 'OD',
    doctorName: 'Dr. Ananya Sharma, MD',
    doctorId: 'DOC-KA-0941',
    imageSource: 'fundus_camera',
    imageUrl: SAMPLE_FUNDUS_IMAGES.MILD_DR,
    quality: {
      focusBlurScore: 90,
      illuminationScore: 92,
      fieldOfViewScore: 91,
      centeringScore: 90,
      overallScore: 91,
      status: 'good',
      reasons: [],
    },
    reviewStatus: 'confirmed_by_doctor',
    isRecaptureNeeded: false,
    aiResult: {
      imageId: 'IMG-SEED-02',
      imageValid: true,
      severity: 'mild',
      icdrLevel: 1,
      confidence: 89,
      trustReport: {
        imageQualityScore: 91,
        modelConfidence: 89,
        lesionEvidenceScore: 85,
        xaiAgreementScore: 90,
        overallTrustScore: 89,
        status: 'ai_supported',
        explanation: 'Stable microaneurysm distribution compared with June 2026 screening.',
        safetyNote: 'AI screening decision support. Physician review confirmed.',
      },
      structures: {
        opticDisc: {
          detected: true,
          confidence: 96,
          location: { x: 73, y: 50, radius: 12 },
          cupToDiscRatio: 0.35,
          statusNotes: 'Normal optic disc morphology.',
        },
        fovea: {
          detected: true,
          confidence: 95,
          location: { x: 44, y: 51, radius: 9 },
          macularEdemaRisk: 'low',
          statusNotes: 'Fovea preserved.',
        },
        bloodVessels: {
          segmented: true,
          tortuosityIndex: 'mild',
          arteriovenousNicking: false,
          caliberScore: 87,
        },
        microaneurysms: {
          detected: true,
          count: 6,
          confidence: 90,
          locations: [
            { id: 'ma-1', type: 'microaneurysm', x: 38, y: 46, confidence: 92, quadrant: 'macular' },
            { id: 'ma-2', type: 'microaneurysm', x: 33, y: 57, confidence: 89, quadrant: 'inferior_temporal' },
          ],
        },
        exudates: {
          detected: false,
          count: 0,
          confidence: 94,
          hasMacularThreat: false,
          locations: [],
        },
        hemorrhages: {
          detected: true,
          count: 2,
          confidence: 86,
          classification: 'dot_blot',
          locations: [],
        },
        neovascularization: {
          detected: false,
          confidence: 99,
          locationType: 'none',
          urgentSurgicalFlag: false,
        },
      },
      evidenceSummary: [
        'Stable microvascular count compared to prior baseline visit',
        'No new retinal lipid deposition or exudate clusters',
      ],
      suggestedReferral: 'routine',
      suggestedFollowUpWeeks: 8,
      managementSuggestion: 'Maintain medical management. Advised HbA1c re-testing.',
      analyzedAt: '2026-08-16T11:22:00Z',
    },
    doctorReview: {
      decision: 'continue_current_plan',
      doctorNotes: 'Condition stable at 2 months. Continuing oral metformin. Advised next follow-up in early October.',
      followUpDate: '2026-10-08',
      doctorName: 'Dr. Ananya Sharma, MD',
      doctorId: 'DOC-KA-0941',
      decidedAt: '2026-08-16T11:30:00Z',
    },
  },

  // Arun Kumar - Visit 3 (Today - October 8, 2026): Moderate DR (Progression Detected!)
  {
    id: 'SCR-2026-0891',
    patientId: 'DR-2026-001245',
    visitNumber: 3,
    date: '2026-10-08',
    time: '09:42 AM',
    timestamp: 1791477720000,
    eye: 'OD',
    doctorName: 'Dr. Ananya Sharma, MD',
    doctorId: 'DOC-KA-0941',
    imageSource: 'fundus_camera',
    imageUrl: SAMPLE_FUNDUS_IMAGES.MILD_DR, // represents current visit
    quality: {
      focusBlurScore: 92,
      illuminationScore: 94,
      fieldOfViewScore: 89,
      centeringScore: 93,
      overallScore: 92,
      status: 'good',
      reasons: [],
    },
    reviewStatus: 'pending_review',
    isRecaptureNeeded: false,
    aiResult: {
      imageId: 'IMG-SEED-03',
      imageValid: true,
      severity: 'moderate',
      icdrLevel: 2,
      confidence: 87,
      trustReport: {
        imageQualityScore: 92,
        modelConfidence: 87,
        lesionEvidenceScore: 84,
        xaiAgreementScore: 90,
        overallTrustScore: 88,
        status: 'ai_supported',
        explanation: 'Progression to Moderate Non-Proliferative DR identified with multiple new microaneurysms, dot-and-blot hemorrhages in inferior temporal quadrant, and early hard exudate cluster.',
        safetyNote: 'AI screening decision support. Final management decision must be made by the doctor.',
      },
      structures: {
        opticDisc: {
          detected: true,
          confidence: 97,
          location: { x: 74, y: 50, radius: 12 },
          cupToDiscRatio: 0.38,
          statusNotes: 'Optic nerve head well-delineated. No signs of neovascularization of the disc (NVD).',
        },
        fovea: {
          detected: true,
          confidence: 93,
          location: { x: 44, y: 51, radius: 9 },
          macularEdemaRisk: 'moderate',
          statusNotes: 'Hard exudates detected within 1.5 disc diameters of foveal center.',
        },
        bloodVessels: {
          segmented: true,
          tortuosityIndex: 'moderate',
          arteriovenousNicking: true,
          caliberScore: 84,
        },
        microaneurysms: {
          detected: true,
          count: 18,
          confidence: 91,
          locations: [
            { id: 'ma-c1', type: 'microaneurysm', x: 38, y: 44, confidence: 93, quadrant: 'macular' },
            { id: 'ma-c2', type: 'microaneurysm', x: 41, y: 42, confidence: 90, quadrant: 'macular' },
            { id: 'ma-c3', type: 'microaneurysm', x: 35, y: 62, confidence: 88, quadrant: 'inferior_temporal' },
            { id: 'ma-c4', type: 'microaneurysm', x: 28, y: 58, confidence: 92, quadrant: 'inferior_temporal' },
            { id: 'ma-c5', type: 'microaneurysm', x: 23, y: 38, confidence: 87, quadrant: 'superior_temporal' },
            { id: 'ma-c6', type: 'microaneurysm', x: 21, y: 66, confidence: 89, quadrant: 'inferior_temporal' },
          ],
        },
        exudates: {
          detected: true,
          count: 7,
          confidence: 88,
          hasMacularThreat: true,
          locations: [
            { id: 'ex-1', type: 'hard_exudate', x: 32, y: 43, radius: 4, confidence: 91, quadrant: 'macular' },
            { id: 'ex-2', type: 'hard_exudate', x: 34, y: 41, radius: 3, confidence: 89, quadrant: 'macular' },
            { id: 'ex-3', type: 'hard_exudate', x: 42, y: 60, radius: 5, confidence: 86, quadrant: 'inferior_temporal' },
          ],
        },
        hemorrhages: {
          detected: true,
          count: 9,
          confidence: 89,
          classification: 'dot_blot',
          locations: [
            { id: 'hem-1', type: 'hemorrhage', x: 39, y: 72, radius: 6, confidence: 92, quadrant: 'inferior_temporal' },
            { id: 'hem-2', type: 'hemorrhage', x: 21, y: 48, radius: 5, confidence: 88, quadrant: 'superior_temporal' },
            { id: 'hem-3', type: 'hemorrhage', x: 59, y: 18, radius: 4, confidence: 85, quadrant: 'superior_nasal' },
          ],
        },
        neovascularization: {
          detected: false,
          confidence: 95,
          locationType: 'none',
          urgentSurgicalFlag: false,
        },
      },
      evidenceSummary: [
        '18 microaneurysms (+12 increase from August screening)',
        '7 discrete hard exudates detected with paramacular proximity',
        '9 dot-and-blot hemorrhages across 2 quadrants',
        'Progression from Mild (ICDR 1) to Moderate (ICDR 2)',
      ],
      suggestedReferral: 'urgent_1_2_weeks',
      suggestedFollowUpWeeks: 4,
      managementSuggestion: 'Comprehensive dilated slit-lamp and OCT examination recommended. Expedited referral to District Hospital Ophthalmology within 1-2 weeks due to disease progression.',
      analyzedAt: '2026-10-08T09:44:00Z',
    },
  },

  // Rajeshwari Patil - Severe Proliferative DR case
  {
    id: 'SCR-2026-0888',
    patientId: 'DR-2026-001247',
    visitNumber: 2,
    date: '2026-10-07',
    time: '04:00 PM',
    timestamp: 1791414000000,
    eye: 'OD',
    doctorName: 'Dr. Ananya Sharma, MD',
    doctorId: 'DOC-KA-0941',
    imageSource: 'fundus_camera',
    imageUrl: SAMPLE_FUNDUS_IMAGES.SEVERE_DR,
    quality: {
      focusBlurScore: 93,
      illuminationScore: 95,
      fieldOfViewScore: 92,
      centeringScore: 94,
      overallScore: 94,
      status: 'good',
      reasons: [],
    },
    reviewStatus: 'referred',
    isRecaptureNeeded: false,
    aiResult: {
      imageId: 'IMG-SEED-04',
      imageValid: true,
      severity: 'severe',
      icdrLevel: 4,
      confidence: 96,
      trustReport: {
        imageQualityScore: 94,
        modelConfidence: 96,
        lesionEvidenceScore: 97,
        xaiAgreementScore: 95,
        overallTrustScore: 95,
        status: 'ai_supported',
        explanation: 'High AI certainty for severe proliferative diabetic retinopathy with neovascular fronds and extensive 4-quadrant hemorrhages.',
        safetyNote: 'AI screening decision support. Immediate specialist referral indicated.',
      },
      structures: {
        opticDisc: {
          detected: true,
          confidence: 98,
          location: { x: 33, y: 50, radius: 13 },
          cupToDiscRatio: 0.42,
          statusNotes: 'Fronds of neovascularization bordering the disc margins (NVD positive).',
        },
        fovea: {
          detected: true,
          confidence: 91,
          location: { x: 62, y: 51, radius: 10 },
          macularEdemaRisk: 'high',
          statusNotes: 'High risk of diabetic macular edema with confluent lipid ring.',
        },
        bloodVessels: {
          segmented: true,
          tortuosityIndex: 'high',
          arteriovenousNicking: true,
          caliberScore: 94,
        },
        microaneurysms: {
          detected: true,
          count: 42,
          confidence: 96,
          locations: [],
        },
        exudates: {
          detected: true,
          count: 28,
          confidence: 95,
          hasMacularThreat: true,
          locations: [],
        },
        hemorrhages: {
          detected: true,
          count: 36,
          confidence: 98,
          classification: 'widespread_4_quadrants',
          locations: [],
        },
        neovascularization: {
          detected: true,
          confidence: 95,
          locationType: 'disc_nvd',
          urgentSurgicalFlag: true,
        },
      },
      evidenceSummary: [
        'Proliferative neovascular fronds (NVD/NVE)',
        'Extensive flame & blot hemorrhages in all 4 quadrants',
        'Multiple cotton wool spots and hard lipid exudates',
        'Urgent vitreo-retina evaluation required',
      ],
      suggestedReferral: 'emergency',
      suggestedFollowUpWeeks: 1,
      managementSuggestion: 'Emergency vitreo-retinal referral for Panretinal Photocoagulation (PRP) / Anti-VEGF intravitreal therapy.',
      analyzedAt: '2026-10-07T16:03:00Z',
    },
    doctorReview: {
      decision: 'refer_to_specialist',
      specialistType: 'Vitreo-Retinal Specialist / Tertiary Eye Hospital',
      referralHospital: 'Minto Ophthalmic Hospital, Regional Institute of Ophthalmology, Bengaluru',
      doctorNotes: 'Urgent referral sent for emergency PRP laser evaluation. Tele-consult slip generated. Patient transport arranged via 108 Arogya Vani.',
      followUpDate: '2026-10-14',
      doctorName: 'Dr. Ananya Sharma, MD',
      doctorId: 'DOC-KA-0941',
      decidedAt: '2026-10-07T16:15:00Z',
    },
  },

  // Lakshmi Devi - Ungradable / Recapture Required Case
  {
    id: 'SCR-2026-0865',
    patientId: 'DR-2026-001249',
    visitNumber: 1,
    date: '2026-10-05',
    time: '12:00 PM',
    timestamp: 1791226800000,
    eye: 'OS',
    doctorName: 'Dr. Ananya Sharma, MD',
    doctorId: 'DOC-KA-0941',
    imageSource: 'fundus_camera',
    imageUrl: SAMPLE_FUNDUS_IMAGES.POOR_QUALITY,
    quality: {
      focusBlurScore: 38,
      illuminationScore: 41,
      fieldOfViewScore: 50,
      centeringScore: 42,
      overallScore: 42,
      status: 'poor',
      reasons: [
        'Severe motion blur and out-of-focus optics',
        'Significant optical underexposure / dark illumination',
        'Macula and optic disc boundaries obscured',
      ],
    },
    reviewStatus: 'pending_review',
    isRecaptureNeeded: true,
  },
];
